# -*- coding: utf-8 -*-
"""
CORE: LANGUAGE PACK
-------------------
Centralizes all text strings for multilingual support.
"""

# The central dictionary containing all translations.
# Each key corresponds to a UI element or message.
# The value is another dictionary with 'gr' and 'en' translations.
LANGUAGE_PACK = {
    # --- General App ---
    "app_title": {"gr": "Mastro Nek AI | Platinum", "en": "Mastro Nek AI | Platinum"},
    "login_tab": {"gr": "Σύνδεση", "en": "Login"},
    "register_tab": {"gr": "Εγγραφή", "en": "Register"},
    "email_lbl": {"gr": "Email", "en": "Email"},
    "pass_lbl": {"gr": "Κωδικός", "en": "Password"},
    "btn_login": {"gr": "Σύνδεση", "en": "Login"},
    "name_lbl": {"gr": "Όνομα", "en": "Name"},
    "btn_register": {"gr": "Εγγραφή", "en": "Register"},
    "reg_success": {"gr": "Η εγγραφή ολοκληρώθηκε! Περιμένετε την έγκριση.", "en": "Registration successful! Awaiting approval."},
    "reg_fail": {"gr": "Αποτυχία εγγραφής. Ελέγξτε τα στοιχεία.", "en": "Registration failed. Check details."},
    "logout": {"gr": "🚪 Αποσύνδεση", "en": "🚪 Logout"},
    "menu_header": {"gr": "Πλοήγηση", "en": "Navigation"},
    "general_ui_error": {"gr": "Προέκυψε σφάλμα στην εμφάνιση: {error}", "en": "An error occurred in the UI: {error}"},
    "db_init_success": {"gr": "Τοπική βάση δεδομένων (SQLite) αρχικοποιήθηκε.", "en": "Local database (SQLite) initialized."},
    "db_init_fail": {"gr": "Αποτυχία αρχικοποίησης τοπικής βάσης δεδομένων.", "en": "Failed to initialize local database."},
    "lang_selector_title": {"gr": "Γλώσσα", "en": "Language"}, # NEW

    # --- License Status ---
    "lic_activated": {"gr": "Άδεια χρήσης ενεργοποιήθηκε!", "en": "License activated!"},
    "lic_expired": {"gr": "Η άδεια χρήσης έχει λήξει.", "en": "License expired."},
    "lic_invalid": {"gr": "Μη έγκυρη άδεια χρήσης.", "en": "Invalid license."},
    "lic_not_found": {"gr": "Δεν βρέθηκε άδεια χρήσης.", "en": "No license found."},
    "lic_pending": {"gr": "Η άδεια είναι σε εκκρεμότητα.", "en": "License is pending."},
    "lic_status_valid": {"gr": "Ενεργή", "en": "Active"},
    "lic_status_expired": {"gr": "Ληγμένη", "en": "Expired"},
    "lic_status_invalid": {"gr": "Μη Έγκυρη", "en": "Invalid"},
    "lic_status_pending": {"gr": "Εκκρεμής", "en": "Pending"},
    "lic_status_not_found": {"gr": "Δεν Βρέθηκε", "en": "Not Found"},

    # --- Menu Items ---
    "menu_dashboard": {"gr": "📊 Επισκόπηση", "en": "📊 Dashboard"},
    "menu_diagnostics": {"gr": "🔧 Διαγνωστικά", "en": "🔧 Diagnostics"},
    "menu_chat": {"gr": "💬 AI Συνομιλία", "en": "💬 AI Chat"},
    "menu_library": {"gr": "🔎 Βιβλιοθήκη Manuals", "en": "🔎 Manuals Library"},
    "menu_clients": {"gr": "📇 Πελατολόγιο", "en": "📇 Client CRM"},
    "menu_organizer": {"gr": "📅 AI Organizer", "en": "📅 AI Organizer"},
    "menu_tools": {"gr": "🛠️ Εργαλεία", "en": "🛠️ Tools"},
    "menu_admin": {"gr": "⚙️ Διαχείριση", "en": "⚙️ Admin Panel"},
    "menu_licensing": {"gr": "🔑 Διαχείριση Αδειών", "en": "🔑 Licensing"},
    "menu_tech_specs": {"gr": "📝 Τεχνικές Προδιαγραφές", "en": "📝 Tech Specs"},
    "menu_help_user": {"gr": "❓ Βοήθεια", "en": "❓ Help"},

    # --- DASHBOARD ---
    'dash_welcome': {'gr': "👋 Καλωσήρθες", 'en': "👋 Welcome"},
    'dash_subtitle': {'gr': "Κέντρο Ελέγχου Τεχνικής Υποστήριξης", 'en': "Technical Support Control Center"},
    'dash_quick': {'gr': "🚀 Γρήγορες Ενέργειες", 'en': "🚀 Quick Actions"},
    'dash_chat_card': {'gr': "AI Τεχνικός Βοηθός", 'en': "AI Technical Assistant"},
    'dash_chat_desc': {'gr': "Διάγνωση βλαβών & Λύσεις", 'en': "Diagnosis & Solutions"},
    'dash_btn_chat': {'gr': "💬 Έναρξη Συνομιλίας", 'en': "💬 Start Chat"},
    'dash_lib_card': {'gr': "Βιβλιοθήκη Manuals", 'en': "Manuals Library"},
    'dash_lib_desc': {'gr': "Αναζήτηση Εγχειριδίων", "en": "Search Manuals"},
    'dash_btn_lib': {'gr': "🔎 Αναζήτηση", 'en': "🔎 Search"},
    'dash_tool_card': {'gr': "Εργαλεία HVAC", 'en': "HVAC Tools"},
    'dash_tool_desc': {'gr': "BTU Calc & Μετατροπές", 'en': "BTU Calc & Converters"},
    'dash_btn_tool': {'gr': "🛠️ Άνοιγμα Εργαλείων", 'en': "🛠️ Open Tools"},
    'dash_status': {'gr': "Κατάσταση Συστήματος: 🟢 Online | AI Engine: Ready", 'en': "System Status: 🟢 Online | AI Engine: Ready"},

    # --- UI Chat (New/Modified Keys) ---
    "chat_context_title": {"gr": "Επιλέξτε Συσκευή Context", "en": "Select Context Device"},
    "brand_label": {"gr": "Μάρκα", "en": "Brand"},
    "model_label": {"gr": "Μοντέλο", "en": "Model"},
    "manuals_found": {"gr": "Βρέθηκαν {count} σχετικά manuals.", "en": "Found {count} related manuals."},
    "no_manuals": {"gr": "Δεν βρέθηκαν σχετικά manuals.", "en": "No manuals found."},
    "select_brand_for_search": {"gr": "Επιλέξτε μάρκα για αναζήτηση.", "en": "Select a brand for search."},
    "tab_text": {"gr": "Κείμενο", "en": "Text"},
    "tab_voice": {"gr": "Φωνή", "en": "Voice"},
    "tab_upload": {"gr": "Upload", "en": "Upload"},
    "voice_input_help": {"gr": "Πατήστε το μικρόφωνο για φωνητική εντολή.", "en": "Click the microphone for voice input."},
    "voice_input_activated": {"gr": "Αναμονή για φωνητική εντολή...", "en": "Waiting for voice input..."},
    "voice_stt_processing": {"gr": "Επεξεργασία φωνητικής εντολής...", "en": "Processing voice input..."},
    "voice_stt_error": {"gr": "Σφάλμα φωνητικής αναγνώρισης: {error}", "en": "Voice recognition error: {error}"},
    "upload_manual_label": {"gr": "Ανεβάστε PDF/Εικόνες", "en": "Upload PDF/Images"},
    "processing_uploaded_file": {"gr": "Επεξεργασία ανεβασμένου αρχείου: '{name}'", "en": "Processing uploaded file: '{name}'"},
    "studying_sources": {"gr": "Μελετώ {count} πηγές...", "en": "Studying {count} sources..."},
    "ai_engine_error": {"gr": "Σφάλμα AI:", "en": "AI Error:"},
    "analyzing": {"gr": "Ανάλυση...", "en": "Analyzing..."},
    "chat_input_placeholder": {"gr": "Περιγράψτε το πρόβλημα ή τον κωδικό βλάβης...", "en": "Describe the issue or error code..."},

    # --- UI Diagnostics (Troubleshooting Wizard) ---
    "diag_title": {"gr": "Διαγνωστικός Οδηγός", "en": "Diagnostic Guide"},
    "diag_subtitle": {"gr": "Βήμα-προς-Βήμα αντιμετώπιση προβλημάτων", "en": "Step-by-step troubleshooting"},
    "diag_start_new": {"gr": "Έναρξη Νέας Διάγνωσης", "en": "Start New Diagnosis"},
    "diag_input_ph": {"gr": "Περιγράψτε το πρόβλημα (π.χ. 'Error E3', 'Δεν ψύχει')", "en": "Describe the problem (e.g. 'Error E3', 'Not cooling')"},
    "diag_context": {"gr": "Ενεργό Context:", "en": "Active Context:"},
    "diag_btn_create": {"gr": "Δημιουργία Πλάνου Διάγνωσης", "en": "Create Diagnosis Plan"},
    "diag_spinner": {"gr": "Δημιουργία πλάνου από AI...", "en": "Generating plan by AI..."},
    "diag_fail": {"gr": "Αδυναμία δημιουργίας πλάνου διάγνωσης.", "en": "Failed to generate diagnosis plan."},
    "diag_step": {"gr": "Βήμα", "en": "Step"},
    "diag_of": {"gr": "από", "en": "of"},
    "diag_done": {"gr": "✅ Η διάγνωση ολοκληρώθηκε!", "en": "✅ Diagnosis complete!"},
    "diag_btn_new": {"gr": "Νέα Διάγνωση", "en": "New Diagnosis"},
    "diag_action": {"gr": "Ενέργεια:", "en": "Action:"},
    "diag_question": {"gr": "Ερώτηση:", "en": "Question:"},
    "diag_yes": {"gr": "✅ Ναι, Διορθώθηκε!", "en": "✅ Yes, Fixed!"},
    "diag_solved_msg": {"gr": "Ωραία δουλειά! Το πρόβλημα λύθηκε.", "en": "Great job! Problem solved."},
    "diag_no": {"gr": "➡️ Όχι, Συνέχεια", "en": "➡️ No, Continue"},
    "diag_cancel": {"gr": "❌ Ακύρωση", "en": "❌ Cancel"},
    "diag_plan_title": {"gr": "Αντιμετώπιση Προβλημάτων", "en": "Troubleshooting"},

    # --- UI Diagnostics AI System Status Section ---
    "diag_ai_section_title": {"gr": "Κατάσταση Συστήματος AI (Gemini)", "en": "AI System Status (Gemini)"},
    "diag_api_key_check": {"gr": "1. Έλεγχος Gemini API Key", "en": "1. Gemini API Key Check"},
    "diag_api_key_found": {"gr": "Το API Key βρέθηκε ({masked_key})", "en": "API Key found ({masked_key})"},
    "diag_api_key_not_found": {"gr": "Δεν βρέθηκε το Gemini API Key.", "en": "Gemini API Key not found."},
    "diag_api_key_info": {"gr": "Φτιάξτε φάκελο .streamlit/secrets.toml και προσθέστε: GEMINI_KEY = 'YOUR_KEY'", "en": "Create .streamlit/secrets.toml and add: GEMINI_KEY = 'YOUR_KEY'"},
    "diag_ai_conn_test": {"gr": "2. Σύνδεση με Google AI (Ping Test)", "en": "2. Google AI Connection (Ping Test)"},
    "diag_ai_conn_attempt": {"gr": "Προσπάθεια σύνδεσης με Google Servers", "en": "Attempting connection to Google Servers"},
    "diag_ai_conn_success": {"gr": "Επιτυχία! Συνδέθηκε και βρήκε {count} διαθέσιμα μοντέλα.", "en": "Success! Connected and found {count} available models."},
    "diag_ai_conn_fail": {"gr": "Αποτυχία Σύνδεσης: {error}", "en": "Connection Failed: {error}"},
    "diag_selected_model": {"gr": "Επιλεγμένο μοντέλο: **{model_name}**", "en": "Selected model: **{model_name}**"},
    "diag_pdf_test": {"gr": "3. Έλεγχος PDF Engine (pypdf)", "en": "3. PDF Engine Check (pypdf)"},
    "diag_pdf_read_success": {"gr": "Το pypdf εγκαταστάθηκε και λειτουργεί.", "en": "pypdf installed and working."},
    "diag_pdf_read_fail": {"gr": "Σφάλμα pypdf: {error}. Εγκαταστήστε με 'pip install pypdf'", "en": "pypdf error: {error}. Install with 'pip install pypdf'"},
    "diag_ai_test_run": {"gr": "4. Προσομοίωση Απάντησης (Test Run)", "en": "4. Response Simulation (Test Run)"},
    "diag_ai_test_query": {"gr": "Στέλνω δοκιμαστική ερώτηση στο {model_name}...", "en": "Sending test query to {model_name}..."},
    "diag_ai_test_success": {"gr": "Το AI απάντησε: '{response}'", "en": "AI responded: '{response}'"},
    "diag_ai_test_empty": {"gr": "Το AI απάντησε αλλά το κείμενο ήταν κενό.", "en": "AI responded but text was empty."},
    "diag_ai_critical_error": {"gr": "ΚΡΙΣΙΜΟ ΣΦΑΛΜΑ AI: {error}", "en": "CRITICAL AI ERROR: {error}"},
    "diag_ai_quota_error": {"gr": "Το πρόβλημα είναι το QUOTA (429). Το κλειδί έχει ξεπεράσει τα όρια.", "en": "Problem is QUOTA (429). Key exceeded limits."},
    "diag_ai_key_invalid": {"gr": "Το κλειδί δεν είναι έγκυρο.", "en": "Key is invalid."},
    "diag_ai_model_not_found": {"gr": "Το μοντέλο δεν βρέθηκε. Δοκιμάστε αναβάθμιση.", "en": "Model not found. Try upgrading."},
    "diag_ai_unknown_error": {"gr": "Άγνωστο σφάλμα δικτύου/συστήματος.", "en": "Unknown network/system error."},

    # --- UI Search ---
    "search_lib_sync_btn": {"gr": "🔄 Sync Library / Ανανέωση Βιβλιοθήκης", "en": "🔄 Sync Library / Refresh Library"},
    "search_sync_spinner": {"gr": "⏳ Σάρωση Drive & Ενημέρωση Ευρετηρίου...", "en": "⏳ Scanning Drive & Updating Index..."},
    "search_sync_success": {"gr": "✅ Ολοκληρώθηκε! Το ευρετήριο ενημερώθηκε. ({count} αρχεία)", "en": "✅ Complete! Index updated. ({count} files)"},
    "search_sync_error": {"gr": "❌ Σφάλμα κατά την ενημέρωση βιβλιοθήκης: {error}", "en": "❌ Error during library sync: {error}"},
    "search_load_spinner": {"gr": "☁️ Φόρτωση Βιβλιοθήκης...", "en": "☁️ Loading Library..."},
    "search_no_data": {"gr": "ℹ️ Δεν βρέθηκαν δεδομένα στη βιβλιοθήκη. Πατήστε 'Sync' για αρχικοποίηση.", "en": "ℹ️ No library data found. Press 'Sync' to initialize."},
    "search_library_empty_warning": {"gr": "⚠️ Η βιβλιοθήκη είναι κενή.", "en": "⚠️ The library is empty."},
    "search_library_sync_info": {"gr": "Το σύστημα προσπαθεί να συγχρονίσει... Αν επιμένει, ειδοποιήστε τον Admin.", "en": "The system is trying to sync... If it persists, notify Admin."},
    "search_stats_expander": {"gr": "📊 Στατιστικά Ευρετηρίου ({count} έγγραφα)", "en": "📊 Index Statistics ({count} documents)"},
    "search_brands": {"gr": "Μάρκες", "en": "Brands"},
    "search_doc_types": {"gr": "Τύποι Εγγράφων", "en": "Document Types"},
    "search_input_ph": {"gr": "π.χ. Daikin Altherma J3 Error", "en": "e.g. Daikin Altherma J3 Error"},
    "search_voice_info": {"gr": "🎧 Λειτουργία φωνητικής αναζήτησης υπό ανάπτυξη...", "en": "🎧 Voice search feature under development..."},
    "search_no_results": {"gr": "Δεν βρέθηκαν αποτελέσματα.", "en": "No results found."},
    "search_recent_files": {"gr": "Πρόσφατα καταχωρημένα αρχεία:", "en": "Recently added files:"},
    "search_file_name": {"gr": "Όνομα αρχείου", "en": "Filename"},
    "search_view_manual": {"gr": "👁️ Προβολή Manual", "en": "👁️ View Manual"},
    "search_download_manual": {"gr": "⬇️ Λήψη Manual", "en": "⬇️ Download Manual"},
    "search_download_error": {"gr": "Σφάλμα κατά τη λήψη: {error}", "en": "Error during download: {error}"},
    "search_docs_found": {"gr": "Βρέθηκαν {count} έγγραφα.", "en": "{count} documents found."},


    # --- UI Admin Panel ---
    "admin_title": {"gr": "⚙️ Διαχείριση Χρηστών & Συστήματος", "en": "⚙️ User & System Administration"},
    "admin_no_users": {"gr": "Δεν βρέθηκαν χρήστες στη βάση δεδομένων.", "en": "No users found in database."},
    "admin_pending": {"gr": "Αιτήματα για Έγκριση", "en": "Pending Approval Requests"},
    "admin_no_pending": {"gr": "Δεν υπάρχουν εκκρεμή αιτήματα χρηστών.", "en": "No pending user requests."},
    "admin_btn_activate": {"gr": "✅ Ενεργοποίηση", "en": "✅ Activate"},
    "admin_btn_delete": {"gr": "❌ Διαγραφή", "en": "❌ Delete"},
    "admin_msg_active": {"gr": "Ο χρήστης ενεργοποιήθηκε", "en": "User activated"},
    "admin_msg_del": {"gr": "Ο χρήστης διαγράφηκε", "en": "User deleted"},
    "admin_all_users": {"gr": "Όλοι οι Εγγεγραμμένοι Χρήστες", "en": "All Registered Users"},
    "admin_all_users_cap": {"gr": "Διαχειριστείτε τους ρόλους των χρηστών.", "en": "Manage user roles."},
    "admin_role_updated": {"gr": "Ο ρόλος του χρήστη {email} ενημερώθηκε σε {role}.", "en": "User {email}'s role updated to {role}."},
    "admin_logs_tab": {"gr": "📊 System Logs", "en": "📊 System Logs"},
    "admin_users_tab": {"gr": "👥 User Management", "en": "👥 User Management"},
    "admin_sync_tab": {"gr": "☁️ Library Sync", "en": "☁️ Library Sync"},
    "admin_maintenance_tab": {"gr": "🔄 Maintenance", "en": "🔄 Maintenance"},
    "admin_audit_logs_subheader": {"gr": "Audit Logs (Security & Usage)", "en": "Audit Logs (Security & Usage)"},
    "admin_no_logs": {"gr": "Δεν βρέθηκαν logs.", "en": "No logs found."},
    "admin_registered_users_subheader": {"gr": "Εγγεγραμμένοι Χρήστες", "en": "Registered Users"},
    "admin_drive_sync_subheader": {"gr": "Google Drive Synchronization", "en": "Google Drive Synchronization"},
    "admin_drive_sync_desc": {"gr": "Χρησιμοποιήστε αυτό το εργαλείο αν η βιβλιοθήκη φαίνεται άδεια ή αν προσθέσατε νέα manuals.", "en": "Use this tool if the library appears empty or if you added new manuals."},
    "admin_current_files_in_memory": {"gr": "Τρέχοντα Αρχεία στη Μνήμη:", "en": "Current Files in Memory:"},
    "admin_btn_force_sync": {"gr": "🚀 FORCE FULL SYNC", "en": "🚀 FORCE FULL SYNC"},
    "admin_missing_modules": {"gr": "Λείπουν Modules (smart_library ή drive). Δεν είναι δυνατός ο συγχρονισμός.", "en": "Missing Modules (smart_library or drive). Cannot sync."},
    "admin_drive_config_missing": {"gr": "Drive Config missing (Folder ID).", "en": "Drive Config missing (Folder ID)."},
    "admin_scanning_drive_spinner": {"gr": "⏳ Σάρωση Google Drive (Μπορεί να πάρει χρόνο)...", "en": "⏳ Scanning Google Drive (This may take time)..."},
    "admin_sync_complete": {"gr": "Ο συγχρονισμός ολοκληρώθηκε! Ευρετηρία {count} αρχεία.", "en": "Sync Complete! Indexed {count} files."},
    "admin_sync_failed": {"gr": "Ο συγχρονισμός απέτυχε: {error}", "en": "Sync Failed: {error}"},
    "admin_software_updates_subheader": {"gr": "Ενημερώσεις Λογισμικού", "en": "Software Updates"},
    "admin_btn_check_github": {"gr": "Check GitHub for Updates", "en": "Check GitHub for Updates"},
    "admin_pulling_repo_spinner": {"gr": "Pulling from repository...", "en": "Pulling from repository..."},
    "admin_new_code_pulled_warning": {"gr": "⚠️ Νέος κώδικας λήφθηκε. Παρακαλώ επανεκκινήστε την εφαρμογή.", "en": "⚠️ New code pulled. Please restart the app."},


    # --- UI Licensing ---
    "lic_page_title": {"gr": "🔑 Διαχείριση Αδειών Χρήσης", "en": "🔑 License Management"},
    "lic_user_section_title": {"gr": "Κατάσταση Άδειας Χρήστη", "en": "User License Status"},
    "lic_status_label": {"gr": "Κατάσταση Άδειας:", "en": "License Status:"},
    "lic_enter_key": {"gr": "Εισάγετε Κλειδί Άδειας Χρήσης", "en": "Enter License Key"},
    "lic_key_ph": {"gr": "π.χ. A1B2C-D3E4F-G5H6I", "en": "e.g. A1B2C-D3E4F-G5H6I"},
    "lic_btn_activate": {"gr": "Ενεργοποίηση Άδειας", "en": "Activate License"},
    "lic_activation_success": {"gr": "Η άδεια ενεργοποιήθηκε επιτυχώς!", "en": "License activated successfully!"},
    "lic_activation_fail": {"gr": "Αποτυχία ενεργοποίησης άδειας", "en": "License activation failed"},
    "lic_admin_section_title": {"gr": "Διαχείριση Αδειών (Admin)", "en": "License Management (Admin)"},
    "lic_admin_no_licenses": {"gr": "Δεν βρέθηκαν άδειες προς διαχείριση.", "en": "No licenses to manage."},
    "lic_admin_all_licenses": {"gr": "Όλες οι Άδειες Χρήσης", "en": "All User Licenses"},
    "lic_admin_filter_users": {"gr": "Φίλτρο Χρηστών (Email, Ρόλος)", "en": "Filter Users (Email, Role)"},
    "lic_admin_user_email": {"gr": "Email", "en": "Email"},
    "lic_admin_current_role": {"gr": "Τρέχων Ρόλος", "en": "Current Role"},
    "lic_admin_new_role": {"gr": "Νέος Ρόλος", "en": "New Role"},
    "lic_admin_role_pending": {"gr": "Εκκρεμής", "en": "Pending"},
    "lic_admin_role_active": {"gr": "Ενεργός", "en": "Active"},
    "lic_admin_role_admin": {"gr": "Διαχειριστής", "en": "Admin"},
    "lic_admin_role_inactive": {"gr": "Ανενεργός", "en": "Inactive"},
    "lic_admin_btn_update_role": {"gr": "Ενημέρωση Ρόλου", "en": "Update Role"},
    "lic_admin_role_update_success": {"gr": "Ο ρόλος ενημερώθηκε επιτυχώς!", "en": "Role updated successfully!"},
    "lic_admin_role_update_fail": {"gr": "Αποτυχία ενημέρωσης ρόλου.", "en": "Failed to update role."},

    # --- UI Organizer ---
    "org_desc": {"gr": "Ο AI Organizer σαρώνει το Google Drive σας, αναλύει τα PDF και τις εικόνες με τεχνητή νοημοσύνη και ταξινομεί αυτόματα τα αρχεία σε δομημένους φακέλους (π.χ. Μάρκα, Μοντέλο, Τύπος Εγχειριδίου). Αυτοματοποιήστε την οργάνωση της βιβλιοθήκης σας!", "en": "The AI Organizer scans your Google Drive, analyzes PDFs and images with AI, and automatically sorts files into structured folders (e.g., Brand, Model, Manual Type). Automate your library organization!"},
    "org_summary_last_run": {"gr": "Σύνοψη Τελευταίας Εκτέλεσης", "en": "Summary of Last Run"},
    "org_last_updated": {"gr": "Τελευταία ενημέρωση:", "en": "Last updated:"},
    "org_files_scanned": {"gr": "Σαρωμένα Αρχεία", "en": "Files Scanned"},
    "org_successfully_sorted": {"gr": "Επιτυχώς Ταξινομημένα", "en": "Successfully Sorted"},
    "org_manual_review": {"gr": "Για Χειροκίνητο Έλεγχο", "en": "For Manual Review"},
    "org_irrelevant_unknown": {"gr": "Άσχετα/Άγνωστα", "en": "Irrelevant/Unknown"},
    "org_duplicates": {"gr": "Διπλότυπα", "en": "Duplicates"},
    "org_detailed_success_dist": {"gr": "Αναλυτική Κατανομή Επιτυχών Ταξινομήσεων", "en": "Detailed Distribution of Successful Sorts"},
    "org_categories_tab": {"gr": "Κατηγορίες", "en": "Categories"},
    "org_brands_tab": {"gr": "Μάρκες", "en": "Brands"},
    "org_types_tab": {"gr": "Τύποι Εγχειριδίων", "en": "Manual Types"},
    "org_no_data_categories": {"gr": "Δεν υπάρχουν δεδομένα για κατηγορίες.", "en": "No data for categories."},
    "org_no_data_brands": {"gr": "Δεν υπάρχουν δεδομένα για μάρκες.", "en": "No data for brands."},
    "org_no_data_types": {"gr": "Δεν υπάρχουν δεδομένα για τύπους εγχειριδίων.", "en": "No data for manual types."},
    "org_start_sorting_subheader": {"gr": "Έναρξη Ταξινόμησης & Οργάνωσης", "en": "Start Sorting & Organizing"},
    "org_warning_active_sort": {"gr": "⚠️ Η ταξινόμηση είναι ήδη σε εξέλιξη.", "en": "⚠️ Sorting is already in progress."},
    "org_start_button": {"gr": "🚀 Έναρξη AI Sorting", "en": "🚀 Start AI Sorting"},
    "org_stop_button": {"gr": "⏹️ Διακοπή", "en": "⏹️ Stop"},
    "org_force_resort_checkbox": {"gr": "Επανεπεξεργασία ΟΛΩΝ των αρχείων (ακόμη και τα ήδη ταξινομημένα)", "en": "Reprocess ALL files (even already sorted ones)"},
    "org_no_files_to_sort": {"gr": "Δεν βρέθηκαν αρχεία για ταξινόμηση στον φάκελο.", "en": "No files found to sort in the root folder."},
    "org_sorting_started": {"gr": "✅ Η ταξινόμηση ξεκίνησε!", "en": "✅ Sorting started!"},
    "org_sorting_stopped": {"gr": "Η ταξινόμηση διακόπηκε από τον χρήστη.", "en": "Sorting stopped by user."},
    "org_sorting_completed": {"gr": "✅ Η ταξινόμηση ολοκληρώθηκε!", "en": "✅ Sorting completed!"},
    "org_browse_files_tab": {"gr": "🔍 Περιήγηση Αρχείων", "en": "🔍 Browse Files"},
    "org_review_errors_tab": {"gr": "⚠️ Αναθεώρηση / Σφάλματα", "en": "⚠️ Review / Errors"},
    "org_full_log_tab": {"gr": "📜 Πλήρες Log", "en": "📜 Full Log"},
    "org_browse_categories": {"gr": "Κατηγορίες", "en": "Categories"},
    "org_browse_brands": {"gr": "Μάρκες", "en": "Brands"},
    "org_browse_models": {"gr": "Μοντέλα", "en": "Models"},
    "org_browse_types": {"gr": "Τύποι Εγχειριδίων", "en": "Manual Types"},
    "org_browse_files_for_category": {"gr": "Αρχεία για Κατηγορία: {category}", "en": "Files for Category: {category}"},
    "org_browse_files_for_brand": {"gr": "Αρχεία για Μάρκα: {brand}", "en": "Files for Brand: {brand}"},
    "org_browse_files_for_model": {"gr": "Αρχεία για Μοντέλο: {model}", "en": "Files for Model: {model}"},
    "org_browse_files_for_type": {"gr": "Αρχεία για Τύπο: {type}", "en": "Files for Type: {type}"},
    "org_back_to_categories": {"gr": "⬅️ Πίσω στις Κατηγορίες", "en": "⬅️ Back to Categories"},
    "org_back_to_brands": {"gr": "⬅️ Πίσω στις Μάρκες", "en": "⬅️ Back to Brands"},
    "org_back_to_models": {"gr": "⬅️ Πίσω στα Μοντέλα", "en": "⬅️ Back to Models"},
    "org_back_to_types": {"gr": "⬅️ Πίσω στους Τύπους", "en": "⬅️ Back to Types"},
    "org_total_files": {"gr": "Σύνολο Αρχείων: {count}", "en": "Total Files: {count}"},
    "org_view_drive": {"gr": "👁️ Προβολή στο Drive", "en": "👁️ View in Drive"},
    "org_manual_review_section": {"gr": "Αρχεία για Χειροκίνητο Έλεγχο", "en": "Files for Manual Review"},
    "org_irrelevant_section": {"gr": "Άσχετα/Άγνωστα Αρχεία", "en": "Irrelevant/Unknown Files"},
    "org_duplicates_section": {"gr": "Διπλότυπα Αρχεία", "en": "Duplicate Files"},
    "org_failed_section": {"gr": "Αποτυχημένα Αρχεία", "en": "Failed Files"},
    "org_no_files_in_category": {"gr": "Δεν βρέθηκαν αρχεία σε αυτή την κατηγορία.", "en": "No files found in this category."},
    "org_full_log_section": {"gr": "Πλήρες Log Εκτέλεσης Organizer", "en": "Full Organizer Run Log"},
    "org_no_log_entries": {"gr": "Δεν υπάρχουν καταχωρήσεις log.", "en": "No log entries."},


    # --- UI Tools ---
    'tool_btu_tab': {'gr': "❄️ BTU Calculator", 'en': "❄️ BTU Calculator"},
    'tool_conv_tab': {'gr': "📏 Μετατροπέας", 'en': "📏 Converter"},
    'tool_pipe_tab': {'gr': "🔥 Σωληνώσεις", 'en': "🔥 Piping Guide"},
    'tool_area': {'gr': "Εμβαδόν Χώρου (m²)", 'en': "Area (m²)"},
    'tool_height': {'gr': "Ύψος (m)", 'en': "Height (m)"},
    'tool_insulation': {'gr': "Μόνωση", 'en': "Insulation"},
    'ins_good': {'gr': "Καλή", 'en': "Good"},
    'ins_avg': {'gr': "Μέτρια", 'en': "Average"},
    'ins_bad': {'gr': "Κακή", 'en': "Poor"},
    'tool_sun': {'gr': "Έκθεση στον Ήλιο", 'en': "Sun Exposure"},
    'sun_low': {'gr': "Χαμηλή", 'en': "Low"},
    'sun_med': {'gr': "Μέτρια", 'en': "Medium"},
    'sun_high': {'gr': "Υψηλή", 'en': "High"},
    'tool_calc_res': {'gr': "Απαιτούμενη Ισχύς", 'en': "Required Power"},
    'tool_rec': {'gr': "Προτεινόμενο κλιματιστικό", 'en': "Recommended AC Unit"},
    'pipe_liquid': {'gr': "Υγρό", 'en': "Liquid"},
    'pipe_gas': {'gr': "Αέριο", 'en': "Gas"},
    "converter_value": {"gr": "Τιμή", "en": "Value"},
    "converter_type": {"gr": "Τύπος", "en": "Type"},
    "converter_bar_psi": {"gr": "Bar -> PSI", "en": "Bar -> PSI"},
    "converter_c_f": {"gr": "C -> F", "en": "C -> F"},
    "converter_kw_btu": {"gr": "kW -> BTU", "en": "kW -> BTU"},
    "piping_guide_title": {"gr": "Οδηγός Σωληνώσεων R32/R410a", "en": "R32/R410a Piping Guide"},


    # --- UI Tech Specs ---
    "specs_title": {"gr": "📝 Τεχνικές Προδιαγραφές Συστήματος", "en": "📝 System Technical Specifications"},
    "specs_arch_title": {"gr": "🧬 Αρχιτεκτονική Συστήματος", "en": "🧬 System Architecture"},
    "specs_status_title": {"gr": "📊 Παρακολούθηση Κατάστασης", "en": "📊 Status Monitor"},
    "specs_python_version": {"gr": "Έκδοση Python", "en": "Python Version"},
    "specs_session_cache": {"gr": "Session Cache", "en": "Session Cache"},
    "specs_user_role": {"gr": "Ρόλος Χρήστη", "en": "User Role"},
    "specs_language": {"gr": "Γλώσσα", "en": "Language"},
    "specs_access_denied": {"gr": "Άρνηση Πρόσβασης.", "en": "Access Denied."},


    # --- UI Help User ---
    "help_title": {"gr": "❓ Κέντρο Βοήθειας", "en": "❓ Help Center"},
    "help_guide_info": {"gr": "ℹ️ Οδηγός Χρήσης Mastro Nek AI", "en": "ℹ️ Mastro Nek AI User Guide"},
    "help_chat_title": {"gr": "💬 Πώς χρησιμοποιώ το Chat;", "en": "💬 How do I use the Chat?"},
    "help_chat_step1": {"gr": "1. Πήγαινε στο μενού 'AI Συνομιλία'.", "en": "1. Go to the 'AI Chat' menu."},
    "help_chat_step2": {"gr": "2. Γράψε την ερώτησή σου στο κάτω μέρος.", "en": "2. Type your question at the bottom."},
    "help_chat_step3": {"gr": "3. Μπορείς να ανεβάσεις φωτογραφίες ή PDF από το tab 'Upload'.", "en": "3. You can upload photos or PDFs from the 'Upload' tab."},
    "help_manuals_title": {"gr": "🔎 Πώς βρίσκω Manuals;", "en": "🔎 How do I find Manuals?"},
    "help_manuals_step1": {"gr": "1. Πήγαινε στη 'Βιβλιοθήκη Manuals'.", "en": "1. Go to the 'Manuals Library'."},
    "help_manuals_step2": {"gr": "2. Γράψε το μοντέλο ή τη μάρκα στη μπάρα αναζήτησης.", "en": "2. Type the model or brand in the search bar."},
    "help_manuals_step3": {"gr": "3. Πάτα το κουμπί 'Προβολή Manual' για να ανοίξει το PDF.", "en": "3. Click the 'View Manual' button to open the PDF."},
    "help_organizer_title": {"gr": "🧠 Πώς λειτουργεί ο Organizer (Admin);", "en": "🧠 How does the Organizer work (Admin)?"},
    "help_organizer_step1": {"gr": "1. Πήγαινε στο 'AI Organizer'.", "en": "1. Go to 'AI Organizer'."},
    "help_organizer_step2": {"gr": "2. Πάτα 'Έναρξη AI Sorting'.", "en": "2. Click 'Start AI Sorting'."},
    "help_organizer_step3": {"gr": "3. Το σύστημα θα διαβάσει τα ατακτοποίητα PDF και θα τα βάλει σε φακέλους αυτόματα.", "en": "3. The system will read unsorted PDFs and organize them into folders automatically."},
}

def get_text(key: str, lang: str = 'gr') -> str:
    """
    Ανακτά το μεταφρασμένο κείμενο για ένα δοσμένο κλειδί και γλώσσα.
    Επιστρέφει το κλειδί αν δεν βρεθεί μετάφραση, για να μην σπάει η εφαρμογή.
    """
    try:
        return LANGUAGE_PACK[key][lang]
    except KeyError:
        # Fallback to English if Greek is missing, or default to key itself
        if lang == 'gr' and key in LANGUAGE_PACK and 'en' in LANGUAGE_PACK[key]:
            return LANGUAGE_PACK[key]['en']
        return f"MISSING_TRANSLATION_{key}"